// Auto-generated by Tegaki. Do not edit manually.
import fontUrl from './cookie.ttf' with { type: 'url' };
import glyphData from './glyphData.json' with { type: 'json' };

const bundle = {
  version: 0,
  family: 'Cookie',
  lineCap: 'round',
  fontUrl,
  fontFaceCSS: `@font-face { font-family: 'Cookie'; src: url(${fontUrl}); }`,
  unitsPerEm: 900,
  ascender: 600,
  descender: 0,
  glyphData,
} as const;

export default bundle;
